spring.application.name=java-monitoring-project

server.address=0.0.0.0
server.port=8080

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
